### ISSUE TITLE
Fix cmake variables used for optional builds

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#104]
Currently, anything optional is done via cmake variables, e.g., `NO_SYSTEM_TUT`, `NO_SYSTEM_TESTU01`, `NO_SYSTEM_HDF5`, `NO_RNGSSE2`, etc. These are cmake booleans, so setting them to true means we will _not_ use them. The double negation can be confusing, especially, via TeamCity, where, e.g., MKL is done via an environment variable, triggering loading of the MKL module, whose behavior is thus the opposite. This should be made more consistent, with a more clear meaning.

**Comment by junghans** [comment]
`NO_SYSTEM_<Package>` is redundant, I guess we should just switch to `CMAKE_DISABLE_FIND_PACKAGE_<Package>=ON`.

**Comment by jbakosi** [comment]
I like `CMAKE_DISABLE_FIND_PACKAGE_<Package>=ON`.

**Comment by jbakosi** [comment]
How about the shorter `CMAKE_DISABLE_<Package>`?

**Comment by junghans** [comment]
Hmm, does that work. I only saw:
```
Every non-REQUIRED ``find_package`` call can be disabled by setting the
:variable:`CMAKE_DISABLE_FIND_PACKAGE_<PackageName>` variable to ``TRUE``.
```
in
https://cmake.org/cmake/help/v3.0/_sources/command/find_package.txt

**Comment by jbakosi** [comment]
Oh, okay! I thought we are just going to invent our own naming for this, instead of relying on cmake. But relying on cmake is even better.

**Comment by junghans** [comment]
Yeah, that is the beauty, we can just get rite of the `if(NO_SYSTEM_XXX)` block and use cmake's built-in.

**Comment by jbakosi** [comment]
Cool, see #105. Did not test this very thoroughly, only with a couple of cmake runs.Better testing will require updating the TeamCity matrix setup to take this into account. Will do that after merge.
