### ISSUE TITLE
Re-enable coverage in travis/docker

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#109]
Okay, my attempt in 481db7167e0 was only partly successful, because now I managed to disable coverage in the travis builds. I don't really know how to change the following line:
```
${COVERAGE:+-DLCOV=/bin/true} \
```
in `docker/Dockerfile.quinoa-build-travis`. I'm tempted to just do `-DCOVERAGE=true`, which is now what would be required to turn on coverage, but the dockerfile is getting this as an environment variable so I'm not sure how to fix it. 

@junghans: should we check for `$ENV{COVERAGE}` as well as the cmake variable `COVERAGE` in cmake code with logical `OR` between them to enable coverage, or the dockerfile can be fixed to pass as I attempt above?

**Comment by junghans** [comment]
That is a bit tricky. In `.travis.yml`, the matrix block defines the build environment and with `--build-arg XXX=${YYY}`, the content of `YYY` is handed into the docker build as the `XXX` variable. The docker build then processes the content of `XXX` with `ARG XXX` and put it back into the environment of the build.
