### ISSUE TITLE
Travis CI pushing to wrong docker repo

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#111]
https://hub.docker.com/r/quinoacomputing/quinoa/tags/ showing two new tags that don't belong there: `gentoo` and `gentoo-clang`. @junghans, could you please fix?

**Comment by junghans** [comment]
To which repo do you want travis to push the docker image after successful builds? (Using `${TRAVIS_SLUG}` just seemed natural.) And under what tags?

**Comment by jbakosi** [comment]
Sorry, I was confused, I thought they were supposed to go to buildenv, but that's an automated build, so nevermind.
