### ISSUE TITLE
Charm++ remove CBase_Foo::pup from Foo::pup

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#119]
From http://charm.cs.illinois.edu/software:

> What's New in 6.7.0
> * Deprecations and Deletions
>   - CBase_Foo::pup need not be called from Foo::pup.

We should remove those calls as that simplifies code. Example: [src/Control/Inciter/CmdLine/CmdLine.h](https://github.com/quinoacomputing/quinoa/blob/master/src/Control/Inciter/CmdLine/CmdLine.h#L116).

**Comment by jbakosi** [comment]
While it is tempting to simply remove those calls, it would be the best if we could write unit tests for making sure the removal of those base-class pups really do still pup the base class as well.

Migration and thus calling pup routines can be triggered by the Charm++ function call `migrateMe()` from inside a Charm++ chare array element. See a commented out example at the bottom of [src/Inciter/Carrier.C](https://github.com/quinoacomputing/quinoa/blob/master/src/Inciter/Carrier.C#L1189). Examples of how to write unit tests that create and "receive" calls to Charm++ objects can be found in [src/UnitTest/tests/Base/TestPUPUtil.h](https://github.com/quinoacomputing/quinoa/blob/master/src/UnitTest/tests/Base/TestPUPUtil.h).

**Comment by stwhite91** [comment]
Along with migrateMe(), a good way to stress test PUP routines / migration is to add an AtSync() call and then run with '+balancer RotateLB'.

**Comment by jbakosi** [comment]
I think I have done this sometime in the past. In either case, we now have many migration tests which will trigger if this is done wrong.
