### ISSUE TITLE
 Implement node-based read of mesh file

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#128]
Explore Charm++'s `ckio` for reading. `ckio`'s `write` is more mature at this point than its `read` (`read` is only on a feature branch) while `write` already on `master`.

More details:

The way I see it at this point, our options are as follows:

1. From a chare group, do a parallel read in which not all group elements participate (how many, e.g., a percentage, controlled by the user),
2. Do the same as 1, but from a node group, using a similar user-adjustable parameter specifying the number of nodes that should participate in the read.
3. Use `ckio`'s `read`.

Of these three options, I assume option 3 would also be able to overlap communication and computation, so ultimately we would probably like that best.. Also as I see, the above is also in the order of increasing complexity, but potentially, also in the order of larger return over investment.

See also https://lists.cs.illinois.edu/lists/arc/charm/2017-03/msg00001.html.

**Comment by jbakosi** [comment]
After talking to @rbuch, the asynchronous read capability in Charm++'s ckio still requires some work before we can use it, which is not a high priority at this point, but will be done in the future. We, however, desperately need something better than file/PE mesh read.

Since we are not certain that asynchronous mesh read will be much of a benefit, we should not wait for this. I think we should go ahead and implement node-based mesh read, which we certainly know will help. I don't even think it is even important to test between file/rank and file/node read with a toy code, as I am pretty certain the latter will outperform the former for large core counts. @rspavel, what do you think?

I also think what I'm simply calling file/node (or node-based) read should definitely be not a simple "every compute node reads a chunk" but a runtime, i.e., command-line-argument, configurable number as to how many readers inciter will use vs. the number of compute cores. I imagine a non-dimensional parameter (a real number) between 0 and 1 should suffice, i.e., [0...1], with the range including both 0 and 1, and 0 corresponding to the least number of PEs reading (i.e., serial read) and 1 corresponding to rank/file read.

**Comment by rspavel** [comment]
This is something that many codes have to deal with and there are likely fairly pluggable solutions we can employ. If current data suggests this is already a significant issue then we should implement something, but I would recommend not putting a lot of effort into things and to instead treat it as a stopgap.

**Comment by jbakosi** [comment]
Done, see https://github.com/quinoacomputing/quinoa/pull/279.
