### ISSUE TITLE
Set up a CI build matrix entry using Charm++'s Randomized Message Queueing

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#131]
See how to build Charm++ with [Randomized Message Queueing](http://charm.cs.illinois.edu/manuals/html/charm++/F.html#SECTION05610000000000000000).

**Comment by jbakosi** [comment]
Additional info from @stwhite91:
>... here's how to actually build with randomized message queues:
```
   ./build charm++ netlrts-linux-x86_64 --with-prio-type=int --enable-randomized-msgq --suffix randq-debug -g
```
> Use of randomized message queues requires the message priority type to not be a bitvector (the default), and the `--suffix` option will be concatenated to the build directory, so this build directory will be named `netlrts-linux-x86_64-randq-debug/`.

**Comment by jbakosi** [comment]
Will do:
- [ ] travis build + unit, & regression test suite run with gnu/release
- [ ] teamcity build + unit, & regression test suite run with gnu/release, with rngsse2, testu01, mkl (turning these three on ensures the most tests)

**Comment by jbakosi** [comment]
https://github.com/quinoacomputing/quinoa-tpl/commit/3802cb471c5ee630f946228b69908c447d6a29e7 enables building Charm++ with randomized queue, using:
```
cmake -DCHARM_EXTRA_ARGS="--with-prio-type=int;--enable-randomized-msgq;--suffix;randq-debug" <path-to-CMakeLists.txt>
```

**Comment by jbakosi** [comment]
@stwhite91: Does randomized queue work (and makes sense) with optimized builds?

**Comment by stwhite91** [comment]
Yes it works and makes sense. It's just a different data structure than the usual FIFO queue with priorities.

**Comment by jbakosi** [comment]
Progress:

Using Clang 4.0.1, libc++, OpenMPI 2.0.2, and Cham++ with randomized message queue:
- [x] `ctest -j36 -R meshconv`
- [x] `ctest -j36 -R rngtest -LE extreme`
- [x]  `ctest -j36 -R walker -E PDF` (skipping those estimating PDFs)
- [ ] `ctest -j36 -R walker`: estimating PDFs fail with
```
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: mis-matched client callbacks in reduction messages
```

**Comment by jbakosi** [comment]
The issue with _walker_, discussed in https://github.com/quinoacomputing/quinoa/issues/131#issuecomment-312877927 is fixed in 09a5bb00. Now all regression tests pass except those testing _inciter_, with randomized message queue:
- [x] `ctest -j36 -E inciter -LE extreme`

**Comment by jbakosi** [comment]
No problems from `unittest` using randomized queue:
- [x] `./charmrun +p36 Main/unittest -v`

**Comment by jbakosi** [comment]
With aeea0eb2 `inciter` runs fine, except those under `regression/inciter/cfl` and `regression/inciter/fct`:
- [x] ctest -j36 -R inciter -E "(cfl|fct)"

**Comment by jbakosi** [comment]
With 9b07e8ea, both unit-, and regression tests pass:
```
scripts/run_tests.sh
```

**Comment by jbakosi** [comment]
Done. See https://github.com/quinoacomputing/quinoa/pull/152.
