### ISSUE TITLE
GCC and Clang have mutually exclusive definitions of how to correctly form a switch statement 

### ISSUE THREAD

**Issue by rfbird** [quinoacomputing/quinoa#158]
GCC wants all switches to have a default case

Clang doesn't want a default case where you cover an enum 

That makes -wError a bit of a problem..

**Comment by junghans** [comment]
Just throw a runtime error in the default case.

**Comment by rfbird** [comment]
If I do that, it will appease GCC, but I'm pretty sure clang will throw a warning that will be promoted to an error about the uselessness of the default, ala:

`/home/quinoa/quinoa/src/Inciter/AMR/tet_store.h:358:29: error: default label in switch which covers all enumeration values [-Werror,-Wcovered-switch-default]
                            default:`

(see https://travis-ci.org/quinoacomputing/quinoa/jobs/260673940)

**Comment by rfbird** [comment]
And conversely gcc:

`/home/quinoa/quinoa/src/Inciter/AMR/tet_store.h:334:32: error: switch missing default case [-Werror=switch-default]
                         switch (master_elements.get(element_id).refinement_case)`

see https://travis-ci.org/quinoacomputing/quinoa/jobs/260795901

**Comment by jbakosi** [comment]
We can just disable `-Wcovered-switch-default` globally for gcc.

**Comment by jbakosi** [comment]
Fixed in 3e4fd1b5.
