### ISSUE TITLE
Put in mesh-locality mesh node reordering

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#172]
Currently, `inciter` has a PE-locality mesh node reordering (see also #171) that attempts to minimize communications during matrix assembly due to PDE operator contributions from Carriers to linear system parts stored and solved on PEs.

Another useful mesh node reordering is to minimize cache misses during PDE operator computations within each Carrier working on a chunk of the mesh. This can be done with the already existing (and tested) wavefront reordering in [Reorder.h](https://github.com/quinoacomputing/quinoa/blob/master/src/Mesh/Reorder.C#L99). What needs to be done is to find a suitable point during setup at which to put this (probably somewhere after the PE-locality reordering but before computation) and to perform the necessary communication required for newly assigned mesh node IDs.

**Comment by ibaned** [comment]
@jbakosi if you link to Omega_h, it includes to do a reordering based on Hilbert space-filling curves, which can be fully parallelized over threads/GPUs and has shown better cache performance after reordering compared to wavefront methods. Just a possibility.

**Comment by jbakosi** [comment]
Thanks, @ibaned, this is definitely a good option to entertain. We are planning to get to this during next summer.

**Comment by jbakosi** [comment]
This is done by "operator reordering", see, e.g., `tests/regression/inciter/compflow/Euler/VorticalFlow/vortical_flow_operator_reorder_diagcg.q`.
