### ISSUE TITLE
Monitor/Track Performance Regression 

### ISSUE THREAD

**Issue by rfbird** [quinoacomputing/quinoa#177]
I think it would be good if we could come up with a way to monitor performance regression.

I'm not sure what software stack is best this (perhaps teamcity?), or how we would best distinguish between the different input decks/solvers/code paths, but I feel like we should be able to get something functional going without too much effort

**Comment by jbakosi** [comment]
I found this, which is about TC + a plugin for being able to fail tests based on performance regression: https://blog.jetbrains.com/dotnet/2015/08/27/performance-profiling-in-continuous-integration-dottrace-and-teamcity/
