### ISSUE TITLE
Reading the side-sets in parallel

### ISSUE THREAD

**Issue by adityakpandare** [quinoacomputing/quinoa#221]
Reading the side-sets in parallel seems to be necessary for the correct reordering of `triinpoel` in `Partitioner::createWorkers()`. 

Here's a rough idea about how we can go about reading the side sets in parallel. There is going to be a significant change required for this though. Here's an approximate list of changes expected for this:

1) ExodusIIMeshReader.C : `readFaces()` and `readSidesetFaces()` will both be parallel and return `nbfac` only for the particular mesh chunk.
2) Transporter.C : calls to `readSidesetFaces()` and `readFaces()` will be gone from here, and so will be `nbfac` and `triinpoel`.
3) Partitioner.C : new calls to `readSidesetFaces()` (which will return `nbfac` for mesh-chunks instead of complete mesh) and `readFaces()` which will return `triinpoel` for mesh-chunk. This is our objective.
4) FaceData.C : `nbfac_complete`, `bface_complete` and `triinpoel_complete` will have to go. Good part is, these aren't needed anywhere else in the code. So that shouldn't be a problem.

However, a question about step 1 above needs to be answered first:
How to read the side-sets only for the specific mesh-chunk? This isn't obvious since the mesh partitioning is done according to nodes, not faces/triangles. Specifically, we need to provide the `side_set_id` to read. Here's the documentation for the API:

https://gsjaardema.github.io/seacas/html/ex__get__partial__side__set_8c.html#a7fefea942566de3c9f657febb4a9aab2

Possible issues arise when a side-set is split between multiple chunks, since this function reads specific side-sets, not specific faces. Couldn't find an API reading specific faces in exodusII.

@jbakosi suggests the following:
We may have to call this API function for all side sets in the file on all PEs since we don't know in advance which side set a given face will be on and throw away those faces that a PE does not hold. The API call will return an error (supposedly correctly) and based on that we can find out if the face was found.

**Comment by jbakosi** [comment]
See also #201.

**Comment by jbakosi** [comment]
Done, see 4978c96b79dae5ea65881a4f9404925c8598df98.
