### ISSUE TITLE
Build system and doc improvements

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#295]
- [x] Document our build process better, in particular, addressing (in one place) what is optional vs required, and also detail potential platform-specific issues, e.g., parallel hdf5 on mac. _Done, see 83843d07._

- [x] Document what options can be influenced with cmake and what cmake expects (or defaults to). _Done, see 83843d07._

- [x] Move as much code as possible from .h to .C files in order to help compile times. Examples:
    - [x] `PDE/[Transport,CompFlow,MultiMat]/[Physics,Problem]/*`. _`PDE/CompFlow/[Physics,Problem]` done by 58bfe2dd, bd256ec1, and fa3c4b8f._ _`PDE/Transport/[Physics,Problem]` done by 79fe7a0a and 53582b66. In addition, 827dc417 moves `PDE/Integrate` to its own build target._
    - [x] `DiffEq/*Policy.h`, also consider orgainizing the files under `DiffEq` into subdirectories by equation types. _Done, see 793d3081, b2847305, and 97970725._

- [x] Strip TPLs to only what we need. E.g., pulling in the full trilinos and root repos (and history) are a huge overkill and makes an initial clone on a new platform awfully slow. We could purge every package from trilinos except Zoltan2 and Exodus, and do a similar purge for root. Boost is also pretty awfully large. We may have to point our git submodules to our own stripped versions or something similar. _Done by extending the documentation on how to _clone_ and _build_ TPLs targeting only specific executables. See 84fbe5d0._

- [x] Add options for building only the TPLs that are needed for a particular target. _Done by https://github.com/quinoacomputing/quinoa-tpl/commit/0e7b97c. Also added to CI, still needs documentation. See #306._

- [x] Rename `.C` to `.cpp` and `.h` to `.hpp`. _Done in ec2f509f._

- [x] Improve doc generation build times. Possibly useful: https://github.com/bahmutov/lcov-filter. _Done by switching from [lcov](http://ltp.sourceforge.net/coverage/lcov.php) to [fastcov](https://github.com/RPGillespie6/fastcov) by https://github.com/quinoacomputing/cmake-modules/commit/25cf62e._

- [x] While building external libraries (previously TPLs) detect flex and bison; and if either is not found do not try to build doxygen and m.css. _Done by https://github.com/quinoacomputing/quinoa-tpl/commit/148f8fe._

- [x] Allow disabling call-, and stack-trace, even in debug, with a command line argument in all executables. _Done by 23124e59._

**Comment by jbakosi** [comment]
CC @adityakpandare

**Comment by jbakosi** [comment]
Remove some of the above and moved to #299.

**Comment by adityakpandare** [comment]
Confirmed that passing ```-DINCITER_ONLY=true``` to Cmake while building external libraries does the right thing; i.e. only builds libraries required by the inciter-executable.

**Comment by jbakosi** [comment]
Cool, thanks for testing it out!

**Comment by adityakpandare** [comment]
Not a problem. Also, can we make the "how to build" link a bit more visible than what it is currently:
"All executables will be under build/Main/. For more information on how to build, see the page on How to build."
For example, something as simple as moving it to the top of the section "Build" as:
"Page on specifics on How to build."
and then this followed by what's in there currently:
"Install prerequisites:..."
can help a lot. What do you think @jbakosi?

**Comment by jbakosi** [comment]
Yeah, good idea. I would also like to add a new top-menu-bar item, similar to "Getting started" at https://doc.magnum.graphics/magnum/.

**Comment by jbakosi** [comment]
@adityakpandare Can you please create an issue so we don't forget it?

**Comment by adityakpandare** [comment]
That would definitely help a lot! :+1:

**Comment by adityakpandare** [comment]
Done. See [#320](https://github.com/quinoacomputing/quinoa/issues/320#issue-454277618).
