### ISSUE TITLE
Comply with the Pitchfork layout

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#299]
See https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs

- [x] The README should contain a description of the contents of the directory and subdirectories. Done, see 4c4cca9e.
- [x] Rename the `regression/` directory to `tests/`. Done, see  345a0c8 .
- [x] Rename `script/` to `tools/`. Done, see 0d0a7639.
- [x] Move `docker/` to `tools/`. Done, see 0d0a7639.
- [x] Rename `tpl/` to `external/`. Done, see 9c384bac.
- [x] For _separate test placement_, move `UnitTest/test/*` to `tests/`. Consider _merged test placement_ for unit tests. Done with _separate test placement_. See 11524921.
- [x] Provide a way to disable the compilation and setting up of tests. Done, see a94f5a57.
- [ ] Move `cmake/` to `tools/`. _Will not do it for now, wait for a consensus/standard on where to put this._
- [ ] Rename `doc/` to `docs/`. _Will not do it for now, I like the singular better._
- [ ] Rename `README.md` to `README`. _Will not do it for now, the `.md` extension works better with rendering tools._
- [ ] Add [examples](https://github.com/quinoacomputing/quinoa-examples) as a git submodule under directory `examples/`. _This would require git-lfs support in the quinoa repo. Incorporating the examples repo is not crucially important at this time, so we hold on with this for now._

**Comment by rfbird** [comment]
I don't have strong feelings about this either way... so .. may as well just do it?

One simple question, why does `examples` imply the need for `git-lfs` if the tests do not?

**Comment by jbakosi** [comment]
> One simple question, why does examples imply the need for git-lfs if the tests do not?

`tests/` is part of the quinoa repo without submodules or subtree. But _examples_ is a separate repo with large files, hence it uses git-lfs, and pulling that in as a submodule into quinoa would require a recursive cloner to supposrt git-lfs which is non-standard git. It is probably possible, but a straightforward attempt to do that failed.

**Comment by adityakpandare** [comment]
+1 for updating the README. I would like the fact that it has an overview of the directory structure. I strongly support the move from ```regression``` and ```UnitTest``` to ```tests```. And I don't think the ```doc``` to ```docs``` would matter, so I'm voting to not change it. About ```tpl``` to ```external```, I haven't worked with many codes that use external libraries; but after a phone-discussion with @jbakosi  yesterday, I agree that ```external``` is better. I'm mostly dispassionate about the other stuff. Thanks for doing this @jbakosi!

**Comment by jbakosi** [comment]
Done, see #300.
