### ISSUE TITLE
Generate a "what's new page" for the docs

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#318]
This can be done by generating a file, listing the recently modified pages, and then pass that to doxygen as input.

As a start, the following is useful for generating the list of files and their modification date:
```
git ls-tree -r --name-only HEAD doc/ | while read filename; do echo "$(git log -1 --format="%ad" -- $filename) $filename"; done
```

Thanks goes to @mosra for the idea.

**Comment by mosra** [comment]
For a hypothetical `[doc skip]` which you would use to mark a commit as "not meant to be shown on the what's new page", passing `--grep="[doc skip]" --invert-grep` to `git log` should filter those out.

**Comment by jbakosi** [comment]
Ah! That is an excellent idea!

**Comment by jbakosi** [comment]
Done by f514ea6. Thanks @mosra for the help with m.css and doxygen. The new section should be visible at https://quinoacomputing.org after CI passes.
