### ISSUE TITLE
Add a "getting started" tab in the documentation menu-bar for easy access

### ISSUE THREAD

**Issue by adityakpandare** [quinoacomputing/quinoa#320]
- [x] Add a new top-menu-bar item, similar to "Getting started" at https://doc.magnum.graphics/magnum/.
- [x] Make the "how to build" link a bit more visible than what it is currently. Simply moving it to the top of the "Build" section will also help. See [comment on #295](https://github.com/quinoacomputing/quinoa/issues/295#issuecomment-500497237).

**Comment by jbakosi** [comment]
Done by bd39232. Also reorganized the top menu bar slightly. You can build target `doc` if you don't want to wait for CI how it looks rendered.

**Comment by adityakpandare** [comment]
Thanks!

**Comment by jbakosi** [comment]
Also, note that I will eliminate the _Page_ top menu item and incorporate the links to where they are relevant -- but for now it is kind of a mess.
