### ISSUE TITLE
Add floating point exception handling (for NaNs)

### ISSUE THREAD

**Issue by adityakpandare** [quinoacomputing/quinoa#337]
Inciter does not throw exceptions when it encounters NaNs in its calculations, and continues time stepping. This can be improved for users if an exception is triggered when a NaN is encountered, and the calculation is stopped at this point. One way to do this is explained [here](https://stackoverflow.com/questions/11933919/debug-c-code-catch-first-nan-appearance), but this might not work well with the charm++ runtime system. A way compatible with charm++ needs to be implemented.
A closely related issue is that once an FPE is used, Timer() triggers it (possibly due to a division by zero), even though the numerical method part does not. This needs to be fixed as well.

**Comment by jbakosi** [comment]
I've been playing with this today and found out that `fenv.h` is part of the standard C++ library. So it should be easy to put this in: include `fenv.h` in `Base/ProcessException.cpp` and do `feenableexcept( FE_ALL_EXCEPT )` in `setSignalHandlers()`.
