### ISSUE TITLE
Abstract Problem::fieldOutput() to a common function for code reuse

### ISSUE THREAD

**Issue by adityakpandare** [quinoacomputing/quinoa#339]
Write a common function for paraview field-outputs for compflow (and similar ones for transport and multimat) corresponding to Problem::fieldOutput(). This would get rid of a lot of repeating code in PDE/CompFlow/Problem/*.cpp. It would also ensure that when a certain field is added in the output for compflow, this doesn't have to be separately done for each problem. A part of the road-map item ["unified field output"](https://quinoacomputing.org/roadmap.html#roadmap_inciter_fieldoutput).

**Comment by adityakpandare** [comment]
See https://github.com/quinoacomputing/quinoa/commit/0592f4be5f18f5e1a9ebba48753cc6eec1aee6c0

**Comment by adityakpandare** [comment]
CompFlow field output abstracted by @WeizhaoLi2018 in https://github.com/quinoacomputing/quinoa/pull/365 (commit https://github.com/quinoacomputing/quinoa/pull/365/commits/9f61e173e68d4ee0219d2b0a2015a969fdedff0e)

**Comment by jbakosi** [comment]
Hey @adityakpandare ! I think this is then now done, right?

**Comment by adityakpandare** [comment]
Yes. Closing it.
