### ISSUE TITLE
Boundary Condition Assignment Error Warning

### ISSUE THREAD

**Issue by WeizhaoLi2018** [quinoacomputing/quinoa#347]
When the control file passes the boundary condition which has not been set up for the specific problem, there is no warnings to indicate that no boundary conditions setup.

For example, there are only bc_sym and bc_extrapolate setup in sodshocktube problem. However even if we give the boundary condition in control file like

     bc_outlet
      sideset 2 4 5 6 end

(Actually, bc_outlet is setup for Compflow but not in sodshocktube problem)
It does not show any warning when running inciter with this control file.

**Comment by jbakosi** [comment]
After #372 is merged, there will be no need for a warning and this problem will go away. See #372 for more details.
