### ISSUE TITLE
Replace vectors of booleans with vectors of integers

### ISSUE THREAD

**Issue by adityakpandare** [quinoacomputing/quinoa#363]
Using a vector of booleans (e.g. ```prelax```) results in erroneous behavior in parallel. This might be because a vector of bools involves some type conversions, which might be getting incorrectly serialized by Charm++. See [this stackexchange post](https://stackoverflow.com/a/17794965) for more details. All such instances of ```std::vector< bool >``` should be replaced by ```std::vector< int >```, to fix this problem. Thank you @jbakosi for helping me figure this out.

**Comment by charest** [comment]
See https://en.cppreference.com/w/cpp/container/vector_bool

Most notably:

- One potential optimization involves coalescing vector elements such that each element occupies a single bit instead of sizeof(bool) bytes. 
- Does not necessarily store its elements as a contiguous array

**Comment by adityakpandare** [comment]
See https://github.com/quinoacomputing/quinoa/pull/364.
