### ISSUE TITLE
Dump all user config to file

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#373]
It would be user-friendly if every run dumped a text file with the state of the parsed command line and input deck for archival and possibly debug purposes.

Mostly important for inciter at this point, but can probably be done uniformly for all executables.

Should be done by outputting TaggedTuple to a file. See also #4 .

**Comment by adityakpandare** [comment]
Should we consider dumping all screen output to a file too?

**Comment by jbakosi** [comment]
That is easily done by appending the command line with
```
2>&1 | tee screenoutput.tty
```

**Comment by adityakpandare** [comment]
Yeah. But I have forgotten to append this so many times, that I think we could write all the screen-output to a file by default.

**Comment by jbakosi** [comment]
Sure. I guess I agree that it _would_ be more user-friendly that way. Will do that too then.

**Comment by adityakpandare** [comment]
Thanks! Let me know if I can help.
