### ISSUE TITLE
Add operator << for tagged tuple

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#4]
For debugging purposes. See STL 5.1.3

**Comment by jbakosi** [comment]
Hey, @nilsdeppe, have you every written an `operator <<` for your tagged tuple?

**Comment by nilsdeppe** [comment]
@jbakosi yes, let me pull out the code quick and I'll share it. Once you have a stream operator for std::tuple the tagged tuple is a straight forward wrapper

**Comment by nilsdeppe** [comment]
Alright, here is the source for `operator<<` for std::tuple:

```cpp
namespace detail {
template <size_t N>
struct TuplePrinter {
  template <typename... Args>
  static std::ostream& print(std::ostream& os, const std::tuple<Args...>& t) {
    TuplePrinter<N - 1>::print(os, t);
    os << ", " << std::get<N - 1>(t);
    return os;
  }
};

template <>
struct TuplePrinter<1> {
  template <typename... Args>
  static std::ostream& print(std::ostream& os, const std::tuple<Args...>& t) {
    os << std::get<0>(t);
    return os;
  }
};
}

template <typename... Args>
inline std::ostream& operator<<(std::ostream& os,
                                const std::tuple<Args...>& t) {
  os << "(";
  StdHelpers_details::TuplePrinter<sizeof...(Args)>::print(os, t);
  os << ")";
  return os;
}
```

and the full implementation of TaggedTuple is:

``` cpp

/// \file
/// Defines class TaggedTuple

#pragma once

#include <tuple>
#include <type_traits>

#include "Parallel/PupStlCpp11.hpp"
#include "Utilities/StdHelpers.hpp"
#include "Utilities/TMPL.hpp"

///
/// \tparam Tags the tags of the objects to be placed in the tuple
template <typename... Tags>
struct TaggedTuple {
  static_assert(tmpl::is_set<Tags...>::value,
                "Cannot create a TaggedTuple with duplicate Tags.");
  template <typename... Args>
  explicit TaggedTuple(Args&&... args) : data_(std::forward<Args>(args)...) {}

  // Call the pup function on the std::tuple
  void pup(PUP::er& p) { p | data_; }  // NOLINT

  /// Gets the size of a TaggedTuple
  /// \return the number of elements in the TaggedTuple
  static constexpr std::size_t size() { return sizeof...(Tags); }

  // @{
  /// Retrieve on object from a TaggedTuple
  ///
  /// \tparam T the tag of the object to retrieve
  /// \return reference to the object held in the tuple
  template <typename T>
  constexpr typename T::type& get() noexcept {
    static_assert(
        not std::is_same<tmpl::index_of<tmpl::list<Tags...>, T>,
                         tmpl::no_such_type_>::value,
        "Could not retrieve Tag from TaggedTuple. See the first template "
        "parameter of the instantiation for what Tag is being "
        "retrieved and the remaining template parameters for what "
        "takes are available.");
    return std::get<tmpl::index_of<tmpl::list<Tags...>, T>::value>(data_);
  }

  template <typename T>
  constexpr const typename T::type& get() const noexcept {
    static_assert(
        not std::is_same<tmpl::index_of<tmpl::list<Tags...>, T>,
                         tmpl::no_such_type_>::value,
        "Could not retrieve Tag from TaggedTuple. See the first template "
        "parameter of the instantiation for what Tag is being "
        "retrieved and the remaining template parameters for what "
        "takes are available.");
    return std::get<tmpl::index_of<tmpl::list<Tags...>, T>::value>(data_);
  }
  // @}

  friend std::ostream& operator<<(std::ostream& os,
                                  const TaggedTuple<Tags...>& t) {
    return os << t.data_;
  }

 private:
  std::tuple<typename Tags::type...> data_;
};

namespace TaggedTuple_detail {
template <typename T>
struct TaggedTupleTypelistImpl;

template <template <typename...> class Ls, typename... Tags>
struct TaggedTupleTypelistImpl<Ls<Tags...>> {
  using type = TaggedTuple<Tags...>;
};
}  // namespace TaggedTuple_detail

template <typename Ls>
using TaggedTupleTypelist =
    typename TaggedTuple_detail::TaggedTupleTypelistImpl<Ls>::type;
```
where the headers `PupStlCpp11.hpp` is for serializing std::tuple (I think we have the same implementation of this), `StdHelpers.hpp` for the streaming of std::tuple, `TMPL.hpp` is a wrapper around brigand that for this case only does

```cpp
/// \cond NEVER
#define BRIGAND_NO_BOOST_SUPPORT
/// \endcond
#include <brigand.hpp>
namespace tmpl = brigand;
```

I'm going to give you access to our private BitBucket repo, the main branch is `feature/spectre_2b` so you can look at things before it's all on GitHub

**Comment by jbakosi** [comment]
Nice! Thanks for sharing. The printer is straightforward indeed as expected.

I also like your implementation of the tagged tuple much better than the one at http://stackoverflow.com/a/13066078, which is what I'm using. There was no brigand at the time and that one also did not rely on boost.mpl but basically pulled its own typelist.

I would also like to switch to brigand from boost.mpl so this will probably be part of that (larger) effort.

**Comment by nilsdeppe** [comment]
You're welcome! Yea, I found that the implementation on SO had a lot of infrastructure that can now be outsourced to a metaprogramming library.

I just looked through Quinoa and the only thing that currently exists only in a test is Cartesian products, but I will look at adding it as a metafunction. I think if that's in replacing `boost::mpl` with `brigand` should work (I can test this once Cartesian product is done).

**Comment by jbakosi** [comment]
I do not entirely understand your motivation. You want to write your own Cartesian product as a meta-function? Do you want that to be part of brigand or something else?

Yeah, I also think replacing boost.mpl with brigand should not be too bad and should clean up some code.

I/We highly appreciate your help but please don't feel obligated to put this in quinoa. ;-)

**Comment by nilsdeppe** [comment]
Sorry, I mean adding it as a metafunction to brigand so it's easier to replace MPL with it.

**Comment by jbakosi** [comment]
Ah! I understand. That would be awesome. Thanks.

**Comment by jbakosi** [comment]
Hey @nilsdeppe: We finally switched to brigand from boost::mpl. Also, cartesian product for two lists is done in https://github.com/edouarda/brigand/blob/master/test/apply.cpp.

Now I will also update our tagged tuple with brigand. Is there any difference with your working version compared to the implementation above?

**Comment by nilsdeppe** [comment]
Yes, the version I implemented is much faster to compile. I would highly recommend taking the one we have over the common implementations on the internet. Feel free to just copy-paste the code over :)
