### ISSUE TITLE
Upgrading to Trilinos 13.4.1

### ISSUE THREAD

**Issue by adityakpandare** [quinoacomputing/quinoa#565]
Upgrade from Trilinos 12.14.1 to [13.4.1](https://github.com/trilinos/Trilinos/releases/tag/trilinos-release-13-4-1).
## Why:
Trilinos pre-13.0 releases have build issues with make versions 4.3 and higher. Newer Linux distros come with GNU make 4.3 by default (e.g. Ubuntu 22.04 ships with GNU make 4.3). See https://github.com/GEOSX/thirdPartyLibs/issues/136 for details about issues building pre-13.0 Trilinos with newer make.

## Solution (see https://github.com/trilinos/Trilinos/issues/11197):
- [x] Determine which Trilinos release builds with newer GNU make version.
- [x] Figure out where the fixes need to be applied.
- [x] Assess if fixes interfere with Charm++ in non-SMP/SMP mode.
- [x] Assess if fixes interfere with load balancing.
- [x] Assess if fixes (calling `Kokkos::initialize()` and `Kokkos::finalize()`) are feasible in the Charm++ framework (depends on the success of the tasks above).
- [x] Assess if changes in trilinos affect regression tests.
- [x] Upgrade Trilinos to [13.4.1](https://github.com/trilinos/Trilinos/releases/tag/trilinos-release-13-4-1) in the [Quinoa TPL repo](https://github.com/quinoacomputing/quinoa-tpl).

**Comment by adityakpandare** [comment]
Confirmed that Trilinos 13.0.1 builds with GNU make 4.3

**Comment by adityakpandare** [comment]
@jbakosi: Upgrading to Trilinos 13.0.1 requires changing the `long`s in the following code: https://github.com/quinoacomputing/quinoa/blob/c3c7ef75fdf18b7b68aff11e6ec3a80a17078c8f/src/LoadBalance/ZoltanInterOp.cpp#L112 https://github.com/quinoacomputing/quinoa/blob/c3c7ef75fdf18b7b68aff11e6ec3a80a17078c8f/src/LoadBalance/ZoltanInterOp.cpp#L143 to `int`s. Do you foresee any problems with this?

**Comment by jbakosi** [comment]
I think Zoltan uses these to index nodes, etc.. I have no idea if this could be a problem (maybe with larger problems when this is used for global IDs). Frankly, if there is a way, I would not mess with it.

**Comment by adityakpandare** [comment]
From what I can see, the only way to not mess with it (and being able to build with newer Make versions) is downgrading Trilinos to 12.12.1 because 12.12.1 builds with GNU Make 4.3. However, I think that is just a lucky combination, and it might not work with future releases of Make. I say this because:
1. At the point when 12.12.1 was released, make 4.3 was not, so most likely they could have tested with the newer Make. Nor was trilinos 12.12.1 updated after make 4.3 released. This means, the fact that 12.12.1 builds with Make 4.3 is just coincidence, and there is a good possibility that it will not play well with future make versions.
2. The fact that the newer trilinos 12.14.1 does not work with make 4.3, but the older one does, supports the above argument.

So rather than downgrading trilinos from 12.14.1 (which is already more than 3 years old) to 12.12.1, and waiting for that also to not build with future GNU makes, I would like to upgrade it to something newer if possible, to have at least some chance of getting support from the trilinos developers in the future regarding any build issues

**Comment by adityakpandare** [comment]
Based on discussions with @jbakosi:
`Kokkos::initialize()` needs to be called in constructor of the `Partitioner` nodegroup; and `Kokkos::finalize()` should be called in `Partitioner`'s destructor.

**Comment by adityakpandare** [comment]
> @jbakosi: Upgrading to Trilinos 13.0.1 requires changing the `long`s in the following code to `int`s:
> 
> https://github.com/quinoacomputing/quinoa/blob/c3c7ef75fdf18b7b68aff11e6ec3a80a17078c8f/src/LoadBalance/ZoltanInterOp.cpp#L112
> 
> https://github.com/quinoacomputing/quinoa/blob/c3c7ef75fdf18b7b68aff11e6ec3a80a17078c8f/src/LoadBalance/ZoltanInterOp.cpp#L143
> 
> Do you foresee any problems with this?

Not necessary to demote to `int` when upgrading to trilinos 13.0.1 or 13.4.1. Can be made to work with `long long`.

**Comment by adityakpandare** [comment]
Exodus's output has somehow changed between trilinos 12.14.1 and 13.4.1: it outputs less nodes in parallel simulations. These might be overlapping nodes shared by partitions. Solutions themselves match with previous ones. But several baselines need to be changed due to different number of nodes. See https://github.com/quinoacomputing/quinoa/commit/dbd51cfa1641e873dd6488d6785395f29e77e9fb.

**Comment by adityakpandare** [comment]
Adding `Kokkos` calls does not affect tests with `migr` (migration), implying load balancing is unaffected.

**Comment by jbakosi** [comment]
> Exodus's output has somehow changed between trilinos 12.14.1 and 13.4.1: it outputs less nodes in parallel simulations. These might be overlapping nodes shared by partitions. Solutions themselves match with previous ones. But several baselines need to be changed due to different number of nodes. See [dbd51cf](https://github.com/quinoacomputing/quinoa/commit/dbd51cfa1641e873dd6488d6785395f29e77e9fb).

Are you sure it is not Zoltan yielding different partitions?

**Comment by adityakpandare** [comment]
> Are you sure it is not Zoltan yielding different partitions?

I compared the mesh-partitions from previous baselines, but doesn't look like it on the surface mesh at least. But it might be the case internally. Although, even if Zoltan does give different partitions, I don't think that's a problem, right?

**Comment by adityakpandare** [comment]
Updating to [trilinos 13.4.1](https://github.com/trilinos/Trilinos/releases/tag/trilinos-release-13-4-1) instead of 13.0.1.

**Comment by jbakosi** [comment]
> > Are you sure it is not Zoltan yielding different partitions?
> 
> I compared the mesh-partitions from previous baselines, but doesn't look like it on the surface mesh at least. But it might be the case internally. Although, even if Zoltan does give different partitions, I don't think that's a problem, right?

No, this is not a problem by itself, but can cause some parallel regression test to fail, because exodiff fails to match, e.g., the number of nodes of a partition.

**Comment by adityakpandare** [comment]
> > > Are you sure it is not Zoltan yielding different partitions?
> > 
> > 
> > I compared the mesh-partitions from previous baselines, but doesn't look like it on the surface mesh at least. But it might be the case internally. Although, even if Zoltan does give different partitions, I don't think that's a problem, right?
> 
> No, this is not a problem by itself, but can cause some parallel regression test to fail, because exodiff fails to match, e.g., the number of nodes of a partition.

Yeah, that might be why I had to update baselines.

**Comment by adityakpandare** [comment]
Update complete. Thanks for your help @jbakosi.
