### ISSUE TITLE
Compilation Error (Inciter Build). Charm build failed

### ISSUE THREAD

**Issue by pkgudla** [quinoacomputing/quinoa#569]
Hi,

I was trying to compile inciter executables on a linux cluster. Below are the installation that were executed:

git clone --branch=develop https://github.com/quinoacomputing/quinoa.git && cd quinoa
 git submodule init && git submodule update && cd external
 git -c submodule."src/pugixml".update=none -c submodule."src/rngsse2".update=none -c submodule."src/testu01".update=none -c submodule."src/tut".update=none -c submodule."src/backward-cpp".update=none -c submodule."src/omega_h".update=none -c submodule."src/doxygen".update=none -c submodule."src/m.css".update=none -c submodule."src/root".update=none -c submodule."src/aec".update=none submodule update --init --recursive

cd quinoa && mkdir external/build && cd external/build
 cmake -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DCMAKE_Fortran_COMPILER=mpif90 -DINCITER_ONLY=true ..
 make -sj$(grep -c processor /proc/cpuinfo)

Here the error messages

[ 32%] Built target numdiff
[ 52%] Built target pegtl
[ 64%] Built target hdf5
[ 64%] Performing build step for 'charm'
[ 68%] Built target highwayhash
CMake Error at /users/PYS0404/com0720/Projects/quinoa/external/build/charm/src/charm-stamp/charm-build-RELEASE.cmake:49 (message):
  Command failed: No such file or directory

   '/users/PYS0404/com0720/Projects/quinoa/external/install/intel-x86_64/charm/buildold' 'charm++' 'mpi-linux-x86_64' '--build-shared' '--with-production' '-j28' '-O3' '-DNDEBUG'

  See also

    /users/PYS0404/com0720/Projects/quinoa/external/build/charm/src/charm-stamp/charm-build-*.log

make[2]: *** [charm/src/charm-stamp/charm-build] Error 1
make[1]: *** [CMakeFiles/charm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 80%] Built target netcdf

For some reason....charm build failed. I checked the charm-build-*.log files, both of them are empty.

Can you point to what I might be doing wrong here. Please note that, I was cloning the "develop" branch

Thx

**Comment by jbakosi** [comment]
Hello @pkgudla,

it looks like charm's install step failed for you. Can you go into `external/install/intel-x86_64/charm/` and rerun their build script `buildold` and see its screen output to see what is missing?

You can see how quinoa's cmake attempted to run `buildold` in `external/build/charm/src/charm-stamp/charm-build-RELEASE.cmake`.

Cheers,
J

**Comment by adityakpandare** [comment]
Hello @pkgudla, is this issue resolved?

**Comment by pkgudla** [comment]
Thank you for you comments. I finally got time to re-ran the compilation instructions and give it another go. I was able to reproduce the same error. When I check it further, "buildold" is itself missing. Infact quinoa/external/install/intel-x86_64/charm/ folder seems completely empty. I also noted following comment at the end of cloning the repo

Unable to checkout '327dc62b5f54a55393074410e6846a78c564fe45' in submodule path 'src/charm'`

The issue seems to be failure to clone charm, resulting in a charm build failure. I have pasted as much info as I can just incase I overlooked something here. Please advise how this can be addressed.

Thanks again in advance for your comments.

------------------------------------------------------------------------------------------------------------------------------------

Here is the command used to clone the repo and tpl specific to "Inciter" tool. 

git clone --branch=develop https://github.com/quinoacomputing/quinoa.git && cd quinoa
git submodule init && git submodule update && cd external
git -c submodule."src/pugixml".update=none -c submodule."src/rngsse2".update=none -c submodule."src/testu01".update=none -c submodule."src/tut".update=none -c submodule."src/backward-cpp".update=none -c submodule."src/omega_h".update=none -c submodule."src/doxygen".update=none -c submodule."src/m.css".update=none -c submodule."src/root".update=none -c submodule."src/aec".update=none -c submodule."src/sol2".update=none submodule update --init --recursive

Here is the complete output after executing the above command (please note the last line)

-bash-4.2$ git -c submodule."src/pugixml".update=none -c submodule."src/rngsse2".update=none -c submodule."src/testu01".update=none -c submodule."src/tut".update=none -c submodule."src/backward-cpp".update=none -c submodule."src/omega_h".update=none -c submodule."src/doxygen".update=none -c submodule."src/m.css".update=none -c submodule."src/root".update=none -c submodule."src/aec".update=none -c submodule."src/sol2".update=none submodule update --init --recursive
Submodule 'cmake' (https://github.com/quinoacomputing/cmake-modules.git) registered for path 'cmake'
Submodule 'src/backward-cpp' (https://github.com/bombela/backward-cpp.git) registered for path 'src/backward-cpp'
Submodule 'src/boost' (https://github.com/quinoacomputing/Boost.git) registered for path 'src/boost'
Submodule 'src/brigand' (https://github.com/edouarda/brigand.git) registered for path 'src/brigand'
Submodule 'src/charm' (https://github.com/UIUC-PPL/charm.git) registered for path 'src/charm'
Submodule 'src/doxygen' (https://github.com/doxygen/doxygen) registered for path 'src/doxygen'
Submodule 'src/exam2m' (https://github.com/Charmworks/ExaM2M.git) registered for path 'src/exam2m'
Submodule 'src/hdf5' (https://github.com/HDFGroup/hdf5.git) registered for path 'src/hdf5'
Submodule 'src/hdf5-ampi' (https://github.com/UIUC-PPL/hdf5-ampi.git) registered for path 'src/hdf5-ampi'
Submodule 'src/highwayhash' (https://github.com/google/highwayhash.git) registered for path 'src/highwayhash'
Submodule 'src/lapack' (https://github.com/Reference-LAPACK/lapack.git) registered for path 'src/lapack'
Submodule 'src/m.css' (https://github.com/mosra/m.css) registered for path 'src/m.css'
Submodule 'src/netcdf' (https://github.com/Unidata/netcdf-c.git) registered for path 'src/netcdf'
Submodule 'src/numdiff' (https://github.com/quinoacomputing/ndiff.git) registered for path 'src/numdiff'
Submodule 'src/pegtl' (https://github.com/taocpp/PEGTL.git) registered for path 'src/pegtl'
Submodule 'src/pugixml' (https://github.com/zeux/pugixml.git) registered for path 'src/pugixml'
Submodule 'src/sol2' (https://github.com/ThePhD/sol2.git) registered for path 'src/sol2'
Submodule 'src/trilinos' (https://github.com/trilinos/Trilinos.git) registered for path 'src/trilinos'
Submodule 'src/tut' (https://github.com/mrzechonek/tut-framework.git) registered for path 'src/tut'
Cloning into 'cmake'...
remote: Enumerating objects: 2955, done.
remote: Counting objects: 100% (149/149), done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 2955 (delta 75), reused 91 (delta 39), pack-reused 2806
Receiving objects: 100% (2955/2955), 733.26 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1879/1879), done.
Submodule path 'cmake': checked out 'eeeaeabd6ec0e0e44253b96be9cbab3f2a6b33be'
Skipping submodule 'src/backward-cpp'
Cloning into 'src/boost'...
remote: Enumerating objects: 106423, done.
remote: Total 106423 (delta 0), reused 0 (delta 0), pack-reused 106423
Receiving objects: 100% (106423/106423), 138.84 MiB | 37.76 MiB/s, done.
Resolving deltas: 100% (65254/65254), done.

Submodule path 'src/boost': checked out '9be6dd96c6d100b586acc5a4e36d30aedaad8667'
Cloning into 'src/brigand'...
remote: Enumerating objects: 3928, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 3928 (delta 44), reused 46 (delta 23), pack-reused 3821
Receiving objects: 100% (3928/3928), 1.10 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2854/2854), done.
Submodule path 'src/brigand': checked out '523ee302474447c808b688607b7353ffd3e5d4bd'
Cloning into 'src/charm'...
remote: Enumerating objects: 217218, done.
remote: Counting objects: 100% (1328/1328), done.
remote: Compressing objects: 100% (523/523), done.
remote: Total 217218 (delta 827), reused 1187 (delta 779), pack-reused 215890
Receiving objects: 100% (217218/217218), 135.79 MiB | 39.94 MiB/s, done.
Resolving deltas: 100% (161304/161304), done.
fatal: reference is not a tree: 327dc62b5f54a55393074410e6846a78c564fe45
Skipping submodule 'src/doxygen'
Cloning into 'src/exam2m'...
remote: Enumerating objects: 1403, done.
remote: Counting objects: 100% (348/348), done.
remote: Compressing objects: 100% (127/127), done.
remote: Total 1403 (delta 232), reused 321 (delta 220), pack-reused 1055
Receiving objects: 100% (1403/1403), 3.80 MiB | 0 bytes/s, done.
Resolving deltas: 100% (958/958), done.
Submodule path 'src/exam2m': checked out 'd016297220933cdbdd982528c0ce781065693931'
Submodule 'external/src/brigand' (https://github.com/edouarda/brigand.git) registered for path 'external/src/brigand'
Submodule 'external/src/charm' (https://github.com/UIUC-PPL/charm.git) registered for path 'external/src/charm'
Submodule 'external/src/hdf5' (https://github.com/HDFGroup/hdf5.git) registered for path 'external/src/hdf5'
Submodule 'external/src/hdf5-ampi' (https://github.com/UIUC-PPL/hdf5-ampi.git) registered for path 'external/src/hdf5-ampi'
Submodule 'external/src/highwayhash' (https://github.com/google/highwayhash.git) registered for path 'external/src/highwayhash'
Submodule 'external/src/lapack' (https://github.com/Reference-LAPACK/lapack.git) registered for path 'external/src/lapack'
Submodule 'external/src/netcdf' (https://github.com/Unidata/netcdf-c.git) registered for path 'external/src/netcdf'
Submodule 'external/src/trilinos' (https://github.com/trilinos/Trilinos.git) registered for path 'external/src/trilinos'
Cloning into 'external/src/brigand'...
remote: Enumerating objects: 3928, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 3928 (delta 44), reused 46 (delta 23), pack-reused 3821
Receiving objects: 100% (3928/3928), 1.10 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2854/2854), done.
Submodule path 'src/exam2m/external/src/brigand': checked out '523ee302474447c808b688607b7353ffd3e5d4bd'
Cloning into 'external/src/charm'...
remote: Enumerating objects: 217218, done.
remote: Counting objects: 100% (1328/1328), done.
remote: Compressing objects: 100% (523/523), done.
remote: Total 217218 (delta 827), reused 1187 (delta 779), pack-reused 215890
Receiving objects: 100% (217218/217218), 135.79 MiB | 38.54 MiB/s, done.
Resolving deltas: 100% (161304/161304), done.
Submodule path 'src/exam2m/external/src/charm': checked out '4bf158d1b773580b32f7c424efdcec86b98ae610'
Cloning into 'external/src/hdf5'...
remote: Enumerating objects: 368379, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 368379 (delta 1), reused 0 (delta 0), pack-reused 368372
Receiving objects: 100% (368379/368379), 240.07 MiB | 43.34 MiB/s, done.
Resolving deltas: 100% (305759/305759), done.
Submodule path 'src/exam2m/external/src/hdf5': checked out '646fc294078f560fc9bef784cb1c4e27cdc51f5b'
Cloning into 'external/src/hdf5-ampi'...
remote: Enumerating objects: 4728, done.
remote: Total 4728 (delta 0), reused 0 (delta 0), pack-reused 4728
Receiving objects: 100% (4728/4728), 14.41 MiB | 18.05 MiB/s, done.
Resolving deltas: 100% (2654/2654), done.
Submodule path 'src/exam2m/external/src/hdf5-ampi': checked out '70077883c5509e57f75a0aecbcb0a043e28ffb98'
Cloning into 'external/src/highwayhash'...
remote: Enumerating objects: 1037, done.
remote: Counting objects: 100% (279/279), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 1037 (delta 234), reused 224 (delta 217), pack-reused 758
Receiving objects: 100% (1037/1037), 583.76 KiB | 0 bytes/s, done.
Resolving deltas: 100% (725/725), done.
Submodule path 'src/exam2m/external/src/highwayhash': checked out '0aaf66bb8a1634ceee4b778df51a652bdf4e1f17'
Cloning into 'external/src/lapack'...
remote: Enumerating objects: 75189, done.
remote: Counting objects: 100% (1191/1191), done.
remote: Compressing objects: 100% (417/417), done.
remote: Total 75189 (delta 855), reused 1015 (delta 773), pack-reused 73998
Receiving objects: 100% (75189/75189), 23.39 MiB | 30.46 MiB/s, done.
Resolving deltas: 100% (70760/70760), done.
Submodule path 'src/exam2m/external/src/lapack': checked out 'aefe75153596de43210057558301efbebcb3793c'
Cloning into 'external/src/netcdf'...
remote: Enumerating objects: 60710, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 60710 (delta 17), reused 33 (delta 17), pack-reused 60667
Receiving objects: 100% (60710/60710), 53.72 MiB | 32.26 MiB/s, done.
Resolving deltas: 100% (46227/46227), done.
Submodule path 'src/exam2m/external/src/netcdf': checked out 'c35e47e4f95aeacc8e7e1d2f531a153f8d7923c8'
Cloning into 'external/src/trilinos'...
remote: Enumerating objects: 1238666, done.
remote: Counting objects: 100% (288/288), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 1238666 (delta 193), reused 235 (delta 162), pack-reused 1238378
Receiving objects: 100% (1238666/1238666), 766.13 MiB | 32.72 MiB/s, done.
Resolving deltas: 100% (938567/938567), done.
Submodule path 'src/exam2m/external/src/trilinos': checked out 'e3c83e3d5caca8f59432f6f5d2e33ae142a16eff'
Cloning into 'src/hdf5'...
remote: Enumerating objects: 368379, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 368379 (delta 1), reused 0 (delta 0), pack-reused 368372
Receiving objects: 100% (368379/368379), 239.89 MiB | 47.43 MiB/s, done.
Resolving deltas: 100% (305748/305748), done.
Submodule path 'src/hdf5': checked out 'a8ee85971b4251a3383d82fdd68bf150e0acad39'
Cloning into 'src/hdf5-ampi'...
remote: Enumerating objects: 4728, done.
remote: Total 4728 (delta 0), reused 0 (delta 0), pack-reused 4728
Receiving objects: 100% (4728/4728), 14.41 MiB | 25.72 MiB/s, done.
Resolving deltas: 100% (2654/2654), done.
Submodule path 'src/hdf5-ampi': checked out '207fb893e3c9abfa80f12a47ca1e14c814a36f30'
Cloning into 'src/highwayhash'...
remote: Enumerating objects: 1037, done.
remote: Counting objects: 100% (279/279), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 1037 (delta 234), reused 224 (delta 217), pack-reused 758
Receiving objects: 100% (1037/1037), 583.76 KiB | 0 bytes/s, done.
Resolving deltas: 100% (725/725), done.
Submodule path 'src/highwayhash': checked out '14dedecd1de87cb662f7a882ea1578d2384feb2f'
Cloning into 'src/lapack'...
remote: Enumerating objects: 75189, done.
remote: Counting objects: 100% (1194/1194), done.
remote: Compressing objects: 100% (422/422), done.
remote: Total 75189 (delta 858), reused 1008 (delta 771), pack-reused 73995
Receiving objects: 100% (75189/75189), 24.82 MiB | 34.28 MiB/s, done.
Resolving deltas: 100% (69915/69915), done.
Submodule path 'src/lapack': checked out 'aefe75153596de43210057558301efbebcb3793c'
Skipping submodule 'src/m.css'
Cloning into 'src/netcdf'...
remote: Enumerating objects: 60710, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 60710 (delta 17), reused 33 (delta 17), pack-reused 60667
Receiving objects: 100% (60710/60710), 53.72 MiB | 31.01 MiB/s, done.
Resolving deltas: 100% (46227/46227), done.
Submodule path 'src/netcdf': checked out 'c35e47e4f95aeacc8e7e1d2f531a153f8d7923c8'
Cloning into 'src/numdiff'...
remote: Enumerating objects: 912, done.
remote: Total 912 (delta 0), reused 0 (delta 0), pack-reused 912
Receiving objects: 100% (912/912), 1014.04 KiB | 0 bytes/s, done.
Resolving deltas: 100% (727/727), done.
Submodule path 'src/numdiff': checked out 'a2be3a91e9f541a7b357f672c21b2e6fa491d794'
Cloning into 'src/pegtl'...
remote: Enumerating objects: 30256, done.
remote: Counting objects: 100% (4240/4240), done.
remote: Compressing objects: 100% (909/909), done.
remote: Total 30256 (delta 3096), reused 4151 (delta 3031), pack-reused 26016
Receiving objects: 100% (30256/30256), 5.53 MiB | 0 bytes/s, done.
Resolving deltas: 100% (21598/21598), done.
Submodule path 'src/pegtl': checked out '26df6aa2d6e582d098b85478a34d4487de8c82c5'
Skipping submodule 'src/pugixml'
Skipping submodule 'src/sol2'
Cloning into 'src/trilinos'...
remote: Enumerating objects: 1238666, done.
remote: Counting objects: 100% (288/288), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 1238666 (delta 193), reused 235 (delta 162), pack-reused 1238378
Receiving objects: 100% (1238666/1238666), 766.13 MiB | 35.18 MiB/s, done.
Resolving deltas: 100% (938567/938567), done.
Submodule path 'src/trilinos': checked out 'e3c83e3d5caca8f59432f6f5d2e33ae142a16eff'
Skipping submodule 'src/tut'
Unable to checkout '327dc62b5f54a55393074410e6846a78c564fe45' in submodule path 'src/charm'

Configuring tpl build with the following options went well and its output is also pasted below

-bash-4.2$ cmake -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DCMAKE_Fortran_COMPILER=mpif90 -DINCITER_ONLY=true -DCHARM_EXTRA_ARGS="--enable-error-checking;--with-prio-type=int;--enable-randomized-msgq;--suffix;randq-debug" -DCHARM_EXTRA_ARGS="smp" -DCHARM_EXTRA_ARGS="--enable-tracing;--enable-commthread-tracing" ..
-- The C compiler identification is Intel 19.0.5.20190815
-- The CXX compiler identification is Intel 19.0.5.20190815
-- The Fortran compiler identification is Intel 19.0.5.20190815
-- Check for working C compiler: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpicc
-- Check for working C compiler: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpicc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpicxx
-- Check for working CXX compiler: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpicxx - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working Fortran compiler: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpif90
-- Check for working Fortran compiler: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpif90 - works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpif90 supports Fortran 90
-- Checking whether /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpif90 supports Fortran 90 - yes
-- CMAKE_BUILD_TYPE not specified, setting to 'Release'
-- Detected OS: "rhel"
-- BUILD_SHARED_LIBS not specified, setting to 'ON'
-- BUILD_SHARED_LIBS: ON
-- Detected target architecture: x86_64
-- CMAKE_INSTALL_PREFIX not specified, setting to '/users/PYS0404/com0720/Projects/quinoa/external/install/intel-x86_64'
-- Found 1 PEs
-- Could NOT find Charm (missing: CHARM_COMPILER CHARM_INCLUDE_DIRS CHARM_RUN) 
-- Charm++ architecture/version: mpi-linux-x86_64
-- Found MPI_C: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpicc (found version "3.1") 
-- Found MPI_CXX: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpicxx (found version "3.1") 
-- Found MPI_Fortran: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpif90 (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- MPI C wrapper: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpicc
-- MPI C++ wrapper: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpicxx
-- MPI Fortran wrapper: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpif90
-- MPI C compiler: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpicc
-- MPI C++ compiler: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpicxx
-- MPI Fortran compiler: /apps/openmpi/intel/19.0/4.0.3-hpcx/bin/mpif90
-- Underlying C compiler: /opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64/icc
-- Underlying C++ compiler: /opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64/icpc
-- Underlying Fortran compiler: /opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64/ifort
-- Charmrun: /users/PYS0404/com0720/Projects/quinoa/external/install/intel-x86_64/charm/bin/charmrun
-- Charm build target: charm++
-- Charm++ extra build args (CHARM_EXTRA_ARGS): --enable-tracing;--enable-commthread-tracing
-- Could NOT find LIBCXX (missing: LIBCXX_LIBRARIES LIBCXXABI_LIBRARIES LIBCXX_INCLUDE_DIRS) 
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib64/libhdf5.so (found version "1.8.12") found components: C HL 
-- HDF5 either not found, not parallel, disabled, or AMPI is enabled: will build
-- Could NOT find NetCDF (missing: NETCDF_INCLUDES) 
-- NetCDF either not found or AMPI is enabled: will build
-- Could NOT find Boost: Found unsuitable version "1.53.0", but required is at least "1.56.0" (found /usr/include)
-- Could NOT find PEGTL: Found unsuitable version "0.0.0", but required is at least "2.0.0" (found )
-- Found MKL: /opt/intel/19.0.5/compilers_and_libraries_2019/linux/mkl/lib/intel64/libmkl_intel_ilp64.so;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/mkl/lib/intel64/libmkl_sequential.so;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/mkl/lib/intel64/libmkl_core.so  
-- Zoltan2, SEACASExodus, and Exodiff either not found or AMPI is enabled: will build
-- Could NOT find NumDiff (missing: NUMDIFF_EXECUTABLE) 
-- Could NOT find HighwayHash (missing: HIGHWAYHASH_INCLUDE_DIRS) 
-- Could NOT find Brigand (missing: BRIGAND_INCLUDE_DIRS) 
-- C compiler flags: '-O3 -DNDEBUG'
-- C++ compiler flags: '-O3 -DNDEBUG'
-- Fortran compiler flags: '-O3'
-- Will build the following 9 TPLs for executable(s) inciter: boost;brigand;charm;hdf5;highwayhash;netcdf;numdiff;pegtl;trilinos
-- Configuring done
-- Generating done
-- Build files have been written to: /users/PYS0404/com0720/Projects/quinoa/external/build

Building tpl failed with charm

[ 44%] Performing configure step for 'highwayhash'
[ 44%] Performing configure step for 'boost'
[ 44%] No configure step for 'charm'
[ 48%] Performing build step for 'charm'
CMake Error at /users/PYS0404/com0720/Projects/quinoa/external/build/charm/src/charm-stamp/charm-build-RELEASE.cmake:49 (message):
  Command failed: No such file or directory

   '/users/PYS0404/com0720/Projects/quinoa/external/install/intel-x86_64/charm/buildold' 'charm++' 'mpi-linux-x86_64' '--enable-tracing' '--enable-commthread-tracing' '--build-shared' '--with-production' '-j1' '-O3' '-DNDEBUG'

  See also

    /users/PYS0404/com0720/Projects/quinoa/external/build/charm/src/charm-stamp/charm-build-*.log


make[2]: *** [charm/src/charm-stamp/charm-build] Error 1
make[1]: *** [CMakeFiles/charm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- highwayhash configure command succeeded.  See also /users/PYS0404/com0720/Projects/quinoa/external/build/highwayhash/src/highwayhash-stamp/highwayhash-configure-*.log
[ 52%] No build step for 'highwayhash'
[ 56%] No install step for 'highwayhash'
[ 56%] Completed 'highwayhash'
[ 56%] Built target highwayhash
[ 56%] No build step for 'brigand'

**Comment by jbakosi** [comment]
I'm not sure why charm, after a successful clone, cannot check out commit 327dc62b5 for you, since it works fine for me. Can you please try the following?

```
git clone --branch=develop https://github.com/quinoacomputing/quinoa.git
cd quinoa
git submodule init && git submodule update
cd external/src/charm
git checkout 327dc62b5f54a55393074410e6846a78c564fe45
```

See if the above runs without error. This is what cmake is doing. If this runs for you fine, you should be able to continue by building the third-party libraries:

```
cd quinoa
mkdir external/build; cd external/build; cmake -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DCMAKE_Fortran_COMPILER=mpif90 .. && make
```

and continue with https://quinoacomputing.github.io/archive/index.html#mainpage_build.

**Comment by pkgudla** [comment]
git clone --branch=develop https://github.com/quinoacomputing/quinoa.git
cd quinoa
git submodule init && git submodule update
cd external/src/charm
git checkout 327dc62b5f54a55393074410e6846a78c564fe45

Tried the above instrction set: After the last instruction here is the error

-bash-4.2$ git checkout 327dc62b5f54a55393074410e6846a78c564fe45
fatal: reference is not a tree: 327dc62b5f54a55393074410e6846a78c564fe45

I checked online...couldn't make sense. I'm using following git --version, if that is anyway relevant

-bash-4.2$ git --version
git version 1.8.3.1

**Comment by adityakpandare** [comment]
Please update your git, and retry the clone from a fresh directory. 1.8.3 is quite dated, and issues might arise due to this.

**Comment by pkgudla** [comment]
Did that....
-bash-4.2$ git --version
git version 2.27.1
-bash-4.2$ git checkout 327dc62b5f54a55393074410e6846a78c564fe45
fatal: reference is not a tree: 327dc62b5f54a55393074410e6846a78c564fe45

**Comment by pkgudla** [comment]
yes i did

gitsh-4.2$ git clone --branch=develop https://github.com/quinoacomputing/quinoa. 
Cloning into 'quinoa'...
remote: Enumerating objects: 92672, done.
remote: Counting objects: 100% (2607/2607), done.
remote: Compressing objects: 100% (576/576), done.
remote: Total 92672 (delta 2054), reused 2555 (delta 2026), pack-reused 90065
Receiving objects: 100% (92672/92672), 217.64 MiB | 27.65 MiB/s, done.
Resolving deltas: 100% (74055/74055), done.
Updating files: 100% (2440/2440), done.
-bash-4.2$ cd quinoa/
-bash-4.2$ git--version
-bash: git--version: command not found
-bash-4.2$ git --version
git version 2.27.1
-bash-4.2$ git submodule init
Submodule 'external' (https://github.com/quinoacomputing/quinoa-tpl) registered for path 'external'
-bash-4.2$ git submodule update
Cloning into '/users/PYS0404/com0720/Projects/quinoa/external'...
Submodule path 'external': checked out '773f67f525bb33497b3798add7dbc957b0419ee9'
-bash-4.2$ cd external/src/charm/
-bash-4.2$ git checkout 327dc62b5f54a55393074410e6846a78c564fe45
fatal: reference is not a tree: 327dc62b5f54a55393074410e6846a78c564fe45
-bash-4.2$

**Comment by adityakpandare** [comment]
Thanks for confirming. Could you check if `git clone --recurse-submodules https://github.com/quinoacomputing/quinoa.git` can create a recursive clone without similar errors? I suspect something amiss with using the recursive clone and excluding submodules in conjunction.

**Comment by jbakosi** [comment]
This is strange and I cannot locally reproduce it. Here is another idea:
```
git clone --recurse-submodules https://github.com/quinoacomputing/quinoa-tpl.git
```
Then copy the whole charm directory from <quinoa-tpl>/src/charm to quinoa/external/src/.

This avoids the git checkout on charm, which is the step that breaks.

**Comment by pkgudla** [comment]
Thank you Joszef and Aditya for your prompt help so far...was very helpful. The issue seems to be with the single core login instance I was using to compile the code. When I instead started using full node (28 core) for running these instructions....everything went well. Didn't have any issue anymore. I might get back to you as I explore the code further. Before that, I have a quick question regarding the time discretization or ODE solvers that are already implemented. Besides TVD RK scheme, are any local time stepping schemes have been explored ?

**Comment by adityakpandare** [comment]
I'm glad your compilation issue was fixed. Feel free to create github/issues if you have further questions. We have the following time discretization schemes implemented in the code:
1. TVDRK3 from Gottlieb and Shu (https://doi.org/10.1090/S0025-5718-98-00913-2) with the Discontinuous Galerkin discretization;
2. TVDRK3 from Waltz et al. (https://doi.org/10.1016/j.compfluid.2013.12.021) with the edge-based finite element discretization (called ALECG);
3. A local time stepping scheme implemented by @jbakosi in the edge-based finite element method.

Most of these details can be found on our inciter doc page https://quinoacomputing.github.io/inciter_main.html.
