### ISSUE TITLE
CMakeLists.txt on the top level of the repo

### ISSUE THREAD

**Issue by gonidelis** [quinoacomputing/quinoa#573]
There is no CMakeLists.txt file the top level of the repo. This results in this command from the docs (https://quinoacomputing.org/#mainpage_build) to be invalid:

 `mkdir external/build; cd external/build; cmake -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DCMAKE_Fortran_COMPILER=mpif90 .. && make; `

I used [this](
https://github.com/quinoacomputing/quinoa-tpl/blob/773f67f525bb33497b3798add7dbc957b0419ee9/CMakeLists.txt) one for reference but it gives me lots of erros. I could expand on these if there is no alternative solution.

**Comment by gonidelis** [comment]
Cloning with recursion on the submodules (`--recurse-submodules`) fixes the problem of course:

`git clone --recurse-submodules https://github.com/quinoacomputing/quinoa.git`

**Comment by adityakpandare** [comment]
The command you are using looks for CMakeLists.txt in the `external/` dir, not the top level dir. `external` uses git submodules to clone the third-party lib repo, and does have a CMakeLists.txt (see https://github.com/quinoacomputing/quinoa-tpl/blob/master/CMakeLists.txt). Can you check that your recursive clone was successful without errors/warnings?
