### ISSUE TITLE
Store initial state of density field for solid materials

### ISSUE THREAD

**Issue by airaudofacundo** [quinoacomputing/quinoa#586]
For 3D cases involving solid materials, a correction source term needs to be computed which uses the value of `rho` for each material at `t=0`. We need some way to store this value to use it in `SolidTerms.cpp`.

**Comment by adityakpandare** [comment]
Done in https://github.com/quinoacomputing/quinoa/commit/bc0df3aedaedc79aaa109e0d2314db500a593b26

**Comment by adityakpandare** [comment]
It would be better to compute `rho0` based on the initial state and store it, rather than accept it as a user input.

**Comment by adityakpandare** [comment]
Done in https://github.com/quinoacomputing/quinoa/commit/9763cfeb9a4a05abf49f4fec29ea66418f3d1fb0.
