### ISSUE TITLE
Use ubuntu's libtestu01-0-dev

### ISSUE THREAD

**Issue by junghans** [quinoacomputing/quinoa#93]
It is in multiverse:
http://packages.ubuntu.com/yakkety/libtestu01-0-dev

**Comment by jbakosi** [comment]
Unsurprisingly, it is also in [debian](https://packages.debian.org/search?keywords=testu01&searchon=names&suite=testing&section=all). However, my fork at https://github.com/quinoacomputing/TestU01-threadsafe makes it thread-safe, which is crucial for the way I'm using it, i.e., [quinoa](https://github.com/quinoacomputing/quinoa) will fail to build without it. I believe the changes to enable thread-safety were at https://github.com/quinoacomputing/TestU01-threadsafe/commit/8e1966763380c80deec0b20792c40a456cd46f78, and I have communicated this to the original author back in February 2014, who replied that 

> I will look at it when time permits.

but I don't think these changes have been added to the official release yet. I also changed a bunch of other minor stuff, e.g., added CMakeLists.txt, etc. See [the list of commits](https://github.com/quinoacomputing/TestU01-threadsafe/commits/master).

So unitl the upstream has these changes, we have to use my fork.

**Comment by junghans** [comment]
@jgmbenoit: could you include these patches in the debian package?

**Comment by jgmbenoit** [comment]
Right now I cannot tell because I am middle of something.
Please submit a [report bug](https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=testu01): you are very lucky that I caught this.

**Comment by junghans** [comment]
Looking at the differences and debian also carries a couple of packages: http://archive.ubuntu.com/ubuntu/pool/multiverse/t/testu01/testu01_1.2.3+ds-2.debian.tar.xz
