### ISSUE TITLE
rngtest fails to run on mac os x

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#96]
As it turns out, our `rngtest` executable has never been tested on Mac OS. ;-)

`rngtest` "builds and links fine" but fails with the following runtime error:

```
54: dyld: lazy symbol binding failed: Symbol not found: _sres_CreatePoisson
54:   Referenced from: /Users/jbakosi/code/quinoa/build/clang/RNGTest/libRNGTest.dylib
54:   Expected in: flat namespace
54: 
54: dyld: Symbol not found: _sres_CreatePoisson
54:   Referenced from: /Users/jbakosi/code/quinoa/build/clang/RNGTest/libRNGTest.dylib
54:   Expected in: flat namespace
```

Note that I have been able successfully fix such errors before, see, e.g., https://github.com/quinoacomputing/quinoa/commit/3c980e36ceeeb0e339feea06e20e77460eb924f3, but I never really understood why the fix worked.

To reproduce this, just try to run our regression suite, e.g.,
```
ctest -j4 -R rngtest:SmallCrush_all_rngsse_pe4 -V
```
which now (after merging the `Random123` work) includes a regression test that exercises the `rngtest` executable.

Mac folks, any ideas?

**Comment by rfbird** [comment]
I just started looking into this and building on mac I got:


In file included from /Users/bird/quinoa/src/Statistics/Statistics.C:26:

In file included from /Users/bird/quinoa/src/Statistics/Statistics.h:66:

In file included from /Users/bird/quinoa/src/Control/StatCtr.h:17:

/Users/bird/quinoa/src/Control/Keywords.h:150:10: fatal error: 'pegtl/contrib/alphabet.hh' file not found

#include <pegtl/contrib/alphabet.hh>

It seems ./tpl/src/pegtl/pegtl/contrib/alphabet.hh does exist but isn't installed to ./tpl/install/clang-x86_64/include/pegtl/

Is this a separate issue or am I missing something?
---
Robert Bird
CCS-7, Mail Stop B287
Los Alamos National Laboratory
Los Alamos, NM 87545

Phone: +1-505-665-7374

**Comment by jbakosi** [comment]
It should be installed in `tpl/install/clang-x86_64/include/pegtl/pegtl/contrib`. `alphabet.hh` was part of the old `PEGTL` (v0.32) from we just switched to the new one (v1.3.1). Please do a re-build of the TPLs, which will install the new version for you.

**Comment by junghans** [comment]
`sres_CreatePoisson` is part of `libtestu01`, so I guess we need to link `libtestu01` against `libRNGTest`.

**Comment by jbakosi** [comment]
Yep, that happens at https://github.com/quinoacomputing/quinoa/blob/master/src/Main/CMakeLists.txt#L175. Note that this only fails on mac (with both gcc and clang).

**Comment by junghans** [comment]
No, you link the _executable_ not the _library_ ! I think, the problem is that `ld` on Mac follows the `gold` policy for linking instead of the `bfd` policy, which is the default on Linux. In `gold` one needs to link the library against the symbols, which it is using directly. However, in C++ it is non-trivial to know what is used directly. On Linux one can get the same behaviour as on Mac by injecting `-Wl,-z,defs` into `LDFLAGS`, which will make `ld` fail if a library has an undefined symbol in it.

**Comment by jbakosi** [comment]
Ah! [This](https://lists.gnu.org/archive/html/libtool/2013-03/msg00008.html) post gave me the clue that mixing static and dynamic libraries on mac is not a good idea. So a1908796fdb makes testu01 mac-aware, so we can build it as a set of dynamic libraries. (This was forced to be static on mac only previously, because I could not figure out at the time how to build dynamic libraries of testu01 on mac.)

Can you guys please pull & test on mac?

**Comment by jbakosi** [comment]
> sres_CreatePoisson is part of libtestu01, so I guess we need to link libtestu01 against libRNGTest.

@junghans But how can `libtestu01` be linked against `libRNGTest`? The former is one of our TPLs and so we only build the latter after the former.

**Comment by jbakosi** [comment]
@junghans While the issue seems to be resolved, I think what you write in https://github.com/quinoacomputing/quinoa/issues/96#issuecomment-273324830, i.e., `-Wl,-z,defs`, should probably still be added on mac. Do you think that is compatible with the trickery at https://github.com/quinoacomputing/quinoa/blob/master/src/CMakeLists.txt#L104?

**Comment by junghans** [comment]
I guess, we need to add 
```
target_link_libraries(RNGTest ${TESTU01_LIBRARY})
```
to `src/RNGTest/CMakeLists.txt`.

**Comment by junghans** [comment]
Or we could make it part of `addCharmModule()`.

**Comment by jbakosi** [comment]
Ah! I think I have tried going down that road, as in https://github.com/quinoacomputing/quinoa/issues/96#issuecomment-273327221, originally, when I first started porting to mac os. However, that seemed to open a can of worms, as now all libraries we build must explicitly specify what other libraries they depend on. This does not seem to be necessary (at least with dynamic linking) on linux (and anywhere else I have ported so far), I guess, because dynamic libraries can also specify other libraries they depend on and the linker just automatically follows those and  links them. I never understood why on mac this does not work this way. Is that correct?

**Comment by junghans** [comment]
I think, we should do a build with `-Wl,-z,defs` on Linux and see if we see the same issues. Having underlinked shared libraries is no-no from the software engineering standpoint. However, every distribution follows a different linker policy, so we will have to fix them down the road.

**Comment by jbakosi** [comment]
I agree. I created https://github.com/quinoacomputing/quinoa/issues/97.
